- name: install {{ pkg_name }}
  block: 
  - name: install {{ pkg_name }}
    yum: 
      name: "{{ pkg_name }}"
      state: latest
  - name: copy template
    template:
      src: haproxy2.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      mode: '0644'
  - name: port open
    firewalld: 
      service: "{{ port_name }}"
      state: enabled
      permanent: true 
      immediate: true
  - name: service start
    service: 
      name: "{{ svc_name }}"
      state: started
      enabled: true
  become: true
  when: inventory_hostname in groups.haproxy
