---
- name: include
  include: haproxy.yml

- name: include web deployment
  include: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: include web deployment in ubuntu
  include: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'
