---
- name: Install WEb Server in Centos and ubuntu
  hosts: web
  become: true
  tasks:
  - name: Install httpd
    yum: 
      name: httpd
      state: latest
    when: ansible_facts.distribution == "CentOS"  # ansible_distribution

  - name: Install apache2 in Ubuntu
    apt: 
     name: apache2
     state: latest
     when: ansible_facts.distribution == "Ubuntu"
