---
- name: copy
  hosts: host1
  become: true
  tasks: 
  - name: download
    get_url:
      url: http://cccr3guro.iptime.org/reg_prac.sh
      dest: /tmp/reg_prac.sh
      mode: u+x

  - name: use shell
    shell: sh /tmp/reg_prac.sh register
    register: reg1

  - name: Debug all
    debug:
      var: reg1.stdout
