---
- name: copy
  hosts: host1
  become: true
  tasks: 
  - name: copy
    copy: 
      src: reg_prac.sh
      dest: /tmp/
      mode: u+x

  - name: use shell
    shell: sh /tmp/reg_prac.sh register
    register: reg1

  - name: Debug all
    debug:
      var: reg1.stdout
