- name: Install ubuntu apache2
  block: 
  - name: install apache2
    apt:
      name: apache2
      state: latest
  - name: ubuntu Port Open
    ufw:
      rule: allow
      port: '80'
      proto: tcp
  - name: Copy index.html
    copy: 
      src: index.html
      dest: /var/www/html
  become: true
