---
- name: test handler use changed_when, changed -> okay
  hosts: host1
  gather_facts: no
  tasks:
  - name: first module
    command: id
    notify: 
    - first
  - name: second module
    debug:
      msg: in the middle
  - name: third module
    command: id
    changed_when: false
    notify: 
    - second

  handlers:
  - name: second
    debug: 
      msg: its second name handler
  - name: first
    debug: 
      msg: its first name handler

